spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: customers-service
              uri: lb://CUSTOMERS
              predicates:
                - Path=/capitec/customer/**
              filters:
                - StripPrefix=2
            - id: accounts-service
              uri: lb://ACCOUNTS
              predicates:
                - Path=/capitec/accounts/**
              filters:
                - StripPrefix=2
            - id: creditcards-service
              uri: lb://CARDS
              predicates:
                - Path=/capitec/creditcards/**
              filters:
                - StripPrefix=2
            - id: loans-service
              uri: lb://LOANS
              predicates:
                - Path=/capitec/loans/**
              filters:
                - StripPrefix=2

server:
  port: 8071

app:
  base-url: "http://localhost:8071"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: read_only
  info:
    env:
      enabled: true

info:
  app:
    name: api-gateway
    description: "Capitec service Gateway Server Application"
    version: "1.0.0"

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
